### ISSUE TITLE
Hey, my friend

### ISSUE THREAD

**Issue by sojoyork** [sojoyork/WildFire#3]
@riccio8 , am americanboi, wanna be my friend again?

Am learning Assembly too!

**Comment by riccio8** [comment]
> @riccio8 , am americanboi, wanna be my friend again?
> 
> Am learning Assembly too!

wdym?

**Comment by sojoyork** [comment]
@riccio8 will you be my friend?

**Comment by riccio8** [comment]
> @riccio8 will you be my friend?

do u need help or something?

**Comment by sojoyork** [comment]
> > @riccio8 will you be my friend?
> 
> do u need help or something?

Am learning assembly too so we can be friends!

**Comment by riccio8** [comment]
> > > @riccio8 will you be my friend?
> > 
> > do u need help or something?
> 
> Am learning assembly too so we can be friends!

it doesn't make sense

**Comment by sojoyork** [comment]
> > > > @riccio8 will you be my friend?
> > > 
> > > 
> > > do u need help or something?
> > 
> > 
> > Am learning assembly too so we can be friends!
> 
> it doesn't make sense

But will you still be my friend?

**Comment by riccio8** [comment]
> > > > > @riccio8 will you be my friend?
> > > > 
> > > > 
> > > > do u need help or something?
> > > 
> > > 
> > > Am learning assembly too so we can be friends!
> > 
> > it doesn't make sense
> 
> But will you still be my friend?

wdym by friend? I mean, I can help u if u want,I don't remember where I first met you

**Comment by sojoyork** [comment]
> > > > > > @riccio8 will you be my friend?
> > > > > 
> > > > > 
> > > > > do u need help or something?
> > > > 
> > > > 
> > > > Am learning assembly too so we can be friends!
> > > 
> > > 
> > > it doesn't make sense
> > 
> > 
> > But will you still be my friend?
> 
> wdym by friend? I mean, I can help u if u want,I don't remember where I first met you

You met me on discord, the username was americanboi

**Comment by riccio8** [comment]
> > > > > > > @riccio8 will you be my friend?
> > > > > > 
> > > > > > 
> > > > > > do u need help or something?
> > > > > 
> > > > > 
> > > > > Am learning assembly too so we can be friends!
> > > > 
> > > > 
> > > > it doesn't make sense
> > > 
> > > 
> > > But will you still be my friend?
> > 
> > wdym by friend? I mean, I can help u if u want,I don't remember where I first met you
> 
> You met me on discord, the username was americanboi

mmmh, oh yeah, I blocked u, u thought u were "a real pro hacker" while u you didn't want to admit you weren't, btw, everyone started from the bottom

**Comment by sojoyork** [comment]
> Contributor



> > > > > > > > @riccio8 will you be my friend?
> > > > > > > 
> > > > > > > 
> > > > > > > do u need help or something?
> > > > > > 
> > > > > > 
> > > > > > Am learning assembly too so we can be friends!
> > > > > 
> > > > > 
> > > > > it doesn't make sense
> > > > 
> > > > 
> > > > But will you still be my friend?
> > > 
> > > 
> > > wdym by friend? I mean, I can help u if u want,I don't remember where I first met you
> > 
> > 
> > You met me on discord, the username was americanboi
> 
> mmmh, oh yeah, I blocked u, u thought u were "a real pro hacker" while u you didn't want to admit you weren't, btw, everyone started from the bottom

I am but am just too stupid to say stuff, that's the problem!

**Comment by riccio8** [comment]
> > Contributor
> 
> 
> 
> > > > > > > > > @riccio8 will you be my friend?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > do u need help or something?
> > > > > > > 
> > > > > > > 
> > > > > > > Am learning assembly too so we can be friends!
> > > > > > 
> > > > > > 
> > > > > > it doesn't make sense
> > > > > 
> > > > > 
> > > > > But will you still be my friend?
> > > > 
> > > > 
> > > > wdym by friend? I mean, I can help u if u want,I don't remember where I first met you
> > > 
> > > 
> > > You met me on discord, the username was americanboi
> > 
> > mmmh, oh yeah, I blocked u, u thought u were "a real pro hacker" while u you didn't want to admit you weren't, btw, everyone started from the bottom
> 
> I am but am just too stupid to say stuff, that's the problem!

that's a proof of what I meant

**Comment by sojoyork** [comment]
> > > Contributor
> > 
> > 
> > > > > > > > > > @riccio8 will you be my friend?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > do u need help or something?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Am learning assembly too so we can be friends!
> > > > > > > 
> > > > > > > 
> > > > > > > it doesn't make sense
> > > > > > 
> > > > > > 
> > > > > > But will you still be my friend?
> > > > > 
> > > > > 
> > > > > wdym by friend? I mean, I can help u if u want,I don't remember where I first met you
> > > > 
> > > > 
> > > > You met me on discord, the username was americanboi
> > > 
> > > 
> > > mmmh, oh yeah, I blocked u, u thought u were "a real pro hacker" while u you didn't want to admit you weren't, btw, everyone started from the bottom
> > 
> > 
> > I am but am just too stupid to say stuff, that's the problem!
> 
> that's a proof of what I meant

BTW am a intermediate hacker now, but am trying my best not to be a script kiddie :(
Will you be my friend again?

**Comment by sojoyork** [comment]
> > > > Contributor
> > > 
> > > 
> > > > > > > > > > > @riccio8 will you be my friend?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > do u need help or something?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Am learning assembly too so we can be friends!
> > > > > > > > 
> > > > > > > > 
> > > > > > > > it doesn't make sense
> > > > > > > 
> > > > > > > 
> > > > > > > But will you still be my friend?
> > > > > > 
> > > > > > 
> > > > > > wdym by friend? I mean, I can help u if u want,I don't remember where I first met you
> > > > > 
> > > > > 
> > > > > You met me on discord, the username was americanboi
> > > > 
> > > > 
> > > > mmmh, oh yeah, I blocked u, u thought u were "a real pro hacker" while u you didn't want to admit you weren't, btw, everyone started from the bottom
> > > 
> > > 
> > > I am but am just too stupid to say stuff, that's the problem!
> > 
> > 
> > that's a proof of what I meant
> 
> BTW am a intermediate hacker now, but am trying my best not to be a script kiddie :( Will you be my friend again?

Okay, let's be friends, tell me where i am too dumb in hacking and where i am being a script kiddie, i will fix/remove that from my career!

**Comment by riccio8** [comment]
> > > > > Contributor
> > > > 
> > > > 
> > > > > > > > > > > > @riccio8 will you be my friend?
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > do u need help or something?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Am learning assembly too so we can be friends!
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > it doesn't make sense
> > > > > > > > 
> > > > > > > > 
> > > > > > > > But will you still be my friend?
> > > > > > > 
> > > > > > > 
> > > > > > > wdym by friend? I mean, I can help u if u want,I don't remember where I first met you
> > > > > > 
> > > > > > 
> > > > > > You met me on discord, the username was americanboi
> > > > > 
> > > > > 
> > > > > mmmh, oh yeah, I blocked u, u thought u were "a real pro hacker" while u you didn't want to admit you weren't, btw, everyone started from the bottom
> > > > 
> > > > 
> > > > I am but am just too stupid to say stuff, that's the problem!
> > > 
> > > 
> > > that's a proof of what I meant
> > 
> > BTW am a intermediate hacker now, but am trying my best not to be a script kiddie :( Will you be my friend again?
> 
> Okay, let's be friends, tell me where i am too dumb in hacking and where i am being a script kiddie, i will fix/remove that from my career!

1. u make code that doesn't really make something 2. an "hacker" as u said  must know a lot of topics well, and the fact that you are learning assembly from python is not very credible 3. when you showed me you were a kid it was not even 2 months ago, you don't learn that much in 2 months

**Comment by sojoyork** [comment]
```python
for i in range(101):
    print("we are still friends", i)

```

**Comment by riccio8** [comment]
> ```python
> for i in range(101):
>     print("we are still friends", i)
> 
> ```

trust me we aren't, and stop otherwise I'll block u
